= multicharge(1)

== Name
multicharge - Atomic partial charge model.


== Synopsis
*multicharge* [_options_] _input_


== Description
Electronegativity equilibration model for atomic partial charges.


== Options

*-m, -model, --model* _model_::
Choose the charge model (eeq or eeqbc)

*-i, -input, --input* _format_::
Hint for the format of the input file

*-c, -charge, --charge* _value_::
Provide the molecular charge

*-s, -solver, --solver* _type_ ::
Provide the partial charge solver: 'CG' or 'DIRECT' (default)

*-it, -maxiter, --maxiter* _int_ ::
Provide the maximal number of iterations

*-tol, -tolerance, --tolerance* _real_ ::
Provide the tolerance of the solver

*-g, -grad, --grad*::
Evaluate molecular gradient and virial. Only for the direct solver.

*-v, -verbosity, --verbosity* _int_ ::
Provide verbosity level of output

*-j, -json, --json*::
Provide output in JSON format to the file 'multicharge.json'

*-version, --version*::
Print program version and exit

*-h, -help, --help*::
Show this help message
