# CMake generated Testfile for 
# Source directory: /home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test
# Build directory: /home/zakharov/Documents/prog/mcharge/multicharge/cmake_build/subprojects/mctc-lib/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(mctc-lib/cutoff "mctc-lib-tester" "cutoff")
set_tests_properties(mctc-lib/cutoff PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/data "mctc-lib-tester" "data")
set_tests_properties(mctc-lib/data PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/math "mctc-lib-tester" "math")
set_tests_properties(mctc-lib/math PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/ncoord "mctc-lib-tester" "ncoord")
set_tests_properties(mctc-lib/ncoord PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read "mctc-lib-tester" "read")
set_tests_properties(mctc-lib/read PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-aims "mctc-lib-tester" "read-aims")
set_tests_properties(mctc-lib/read-aims PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-cjson "mctc-lib-tester" "read-cjson")
set_tests_properties(mctc-lib/read-cjson PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-ctfile "mctc-lib-tester" "read-ctfile")
set_tests_properties(mctc-lib/read-ctfile PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-gaussian "mctc-lib-tester" "read-gaussian")
set_tests_properties(mctc-lib/read-gaussian PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-genformat "mctc-lib-tester" "read-genformat")
set_tests_properties(mctc-lib/read-genformat PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-json "mctc-lib-tester" "read-json")
set_tests_properties(mctc-lib/read-json PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-pdb "mctc-lib-tester" "read-pdb")
set_tests_properties(mctc-lib/read-pdb PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-pymatgen "mctc-lib-tester" "read-pymatgen")
set_tests_properties(mctc-lib/read-pymatgen PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-qchem "mctc-lib-tester" "read-qchem")
set_tests_properties(mctc-lib/read-qchem PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-qcschema "mctc-lib-tester" "read-qcschema")
set_tests_properties(mctc-lib/read-qcschema PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-turbomole "mctc-lib-tester" "read-turbomole")
set_tests_properties(mctc-lib/read-turbomole PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-vasp "mctc-lib-tester" "read-vasp")
set_tests_properties(mctc-lib/read-vasp PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/read-xyz "mctc-lib-tester" "read-xyz")
set_tests_properties(mctc-lib/read-xyz PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/symbols "mctc-lib-tester" "symbols")
set_tests_properties(mctc-lib/symbols PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write "mctc-lib-tester" "write")
set_tests_properties(mctc-lib/write PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-aims "mctc-lib-tester" "write-aims")
set_tests_properties(mctc-lib/write-aims PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-cjson "mctc-lib-tester" "write-cjson")
set_tests_properties(mctc-lib/write-cjson PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-ctfile "mctc-lib-tester" "write-ctfile")
set_tests_properties(mctc-lib/write-ctfile PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-gaussian "mctc-lib-tester" "write-gaussian")
set_tests_properties(mctc-lib/write-gaussian PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-genformat "mctc-lib-tester" "write-genformat")
set_tests_properties(mctc-lib/write-genformat PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-pdb "mctc-lib-tester" "write-pdb")
set_tests_properties(mctc-lib/write-pdb PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-pymatgen "mctc-lib-tester" "write-pymatgen")
set_tests_properties(mctc-lib/write-pymatgen PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-qchem "mctc-lib-tester" "write-qchem")
set_tests_properties(mctc-lib/write-qchem PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-qcschema "mctc-lib-tester" "write-qcschema")
set_tests_properties(mctc-lib/write-qcschema PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-turbomole "mctc-lib-tester" "write-turbomole")
set_tests_properties(mctc-lib/write-turbomole PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-vasp "mctc-lib-tester" "write-vasp")
set_tests_properties(mctc-lib/write-vasp PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
add_test(mctc-lib/write-xyz "mctc-lib-tester" "write-xyz")
set_tests_properties(mctc-lib/write-xyz PROPERTIES  _BACKTRACE_TRIPLES "/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;72;add_test;/home/zakharov/Documents/prog/mcharge/multicharge/subprojects/mctc-lib/test/CMakeLists.txt;0;")
